graph LR
    A[CONFIGURATION] --> B(Engines)
    A --> C(Avatars)

    B --> B1[Tarot.json]
    B --> B2[Gene Keys.json]
    B --> B3[Enneagram.json]

    C --> C1[Name]
    C --> C2[Archetype]
    C --> C3[Attributes]
