graph LR
    A[AVATARS] --> B(Data Structure)

    B --> B1[Name]
    B --> B2[Archetype]
    B --> B3[Description]
    B --> B4[Attributes]

    B4 --> B41[Intelligence]
    B4 --> B42[Wisdom]
    B4 --> B43[Compassion]
