graph LR
    A[FIELDWORK] --> B(Daily Practices)

    B --> B1[Upon Waking]
    B --> B2[Midday]
    B --> B3[Before Sleep]

    B1 --> B11[3-minute Breathfield Calibration]
    B2 --> B21[Compass Check]
    B3 --> B31[3-breath Reflection]
